### ISSUE TITLE
Create basic todo web app using NEAP stack

### ISSUE THREAD

**Issue by adam-edison** [adam-edison/thousand-miles#1]
Following this:
* http://mherman.org/blog/2015/02/12/postgresql-and-nodejs/#.WZoM6CiGOUm

* [ ] Go through tutorial from start to finish, making commits along the way
* [ ] Version control the libraries downloaded as a separate repo
* [ ] Refactor as necessary

**Comment by adam-edison** [comment]
### Worked Entirely in Git Bash (Not Node Js Prompt)
### Used source links:
* http://expressjs.com/en/starter/generator.html
* http://expressjs.com/en/guide/using-template-engines.html

1. `npm install express-generator -g`
1. `express --view=pug thousand-miles` (answered `y` because we're inside my git project root)
1. `cd thousand-miles`
1. `npm install`
1. `DEBUG=thousand-miles:* npm start`
1. http://localhost:3000/   - success!

**Comment by adam-edison** [comment]
Whoops! I was working on the master branch. I could solo this thing, but I like to use feature branches, one per issue. I'll just use feature branches from now on.

**Comment by adam-edison** [comment]
1. `npm install supervisor -g`
1. Changed scripts property in package.json to use `supervisor` instead of `node` command

**Comment by adam-edison** [comment]
1. Installed PostgreSQL
  * https://www.enterprisedb.com/downloads/postgres-postgresql-downloads#windows

**Comment by adam-edison** [comment]
Coming up...
* https://stackoverflow.com/questions/19578796/what-is-the-save-option-for-npm-install
* npm install pg@6.1.0 --save

**Comment by adam-edison** [comment]
I'm adding the node_modules to the repository. It's necessary to version control dependencies on any project if you intend to ship it as a complete product. Yes. someone can npm install and get the updated packages if they want to develop on a different system. And yes, that will involve a change to those packages. If need be, I can always choose to remove the folder in a later commit, and place the contents under a separate repository - separate repos for each system supported in case of OS-specific binary files.

**Comment by adam-edison** [comment]
Ran into issue with latest pg:

```
query.on('end', () => { client.end(); });
      ^
TypeError: query.on is not a function
```

Suggested fix is to revert to v6, so I'll follow the tutorial versions more carefully, now.
Apparently these package producers don't necessarily care about backwards compatibility.

**Comment by adam-edison** [comment]
`````
$ node models/database.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

error: password authentication failed for user "aedison"
    at Connection.parseE (C:\development\thousand-miles\node_modules\pg\lib\connection.js:554:11)
    at Connection.parseMessage (C:\development\thousand-miles\node_modules\pg\lib\connection.js:381:17)
    at Socket.<anonymous> (C:\development\thousand-miles\node_modules\pg\lib\connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

**Comment by adam-edison** [comment]
I guess that means I need to set up my user for authentication against the database. Makes sense.  
I could alternately use my code to configure the user and password...

**Comment by adam-edison** [comment]
I really want to configure a test user to connect with.  
It seems to default to environment variables (bleh!).  
So I'm going to build an external config file and read it in:

* https://node-postgres.com/features/connecting

**Comment by adam-edison** [comment]
This is also extremely helpful:
* https://node-postgres.com/features/pooling

It makes sense to me to use a Pool instead of a client, right away. "Measure twice, cut one."

**Comment by adam-edison** [comment]
The easiest way by far, it seems, to deal with a connection is to use a connection string.  
* https://node-postgres.com/features/connecting#connection-uri

That's storing one piece of information (like Drupal and Wordpress do), instead of storing 6 variables that have to read in as key-value pairs.

I'll have to see what options I have for key-value stores locally that won't be version-controlled.  
I'm surprised at Express - it doesn't do much. I was expecting more of an auto-wiring, like in Rails.  
Guess I just need to search for  good node module.

**Comment by adam-edison** [comment]
This seems like a great, flexible, powerful properties file reader:
* https://www.npmjs.com/package/properties

**Comment by adam-edison** [comment]
Also, this tutorial leaves out a TON of information. It's a good thing I'm not a beginner,
